/**
 *  Copyright (c) 2023 Michael Malloy, Enter-Name
 *  CNIT 25501 Final Project - GET THE bagel
 */

import javax.swing.JOptionPane;

public class PuzzleScreen extends javax.swing.JFrame {
    
    static Puzzle puzzle = null;
    static Player Ted = null;
    
    private static int incorrectAnswers;
    
    enum Status {
        Correct,
        Incorrect,
        Skipped,
        OutOfHealth,
        WinCon
    }
    
    /**
     * Creates new form Controller
     */
    public PuzzleScreen(Player TedRose) {
        Ted = TedRose;
        initComponents();
        startPuzzle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        puzzleDisplay = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        AnswerBox = new javax.swing.JTextField();
        SubmitAnswerButton = new javax.swing.JButton();
        SkipButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFileDropdown = new javax.swing.JMenu();
        quitMenuButton = new javax.swing.JMenuItem();
        menuEditDropdown = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("[Bagel] - Development Build");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(400, 200));

        jSplitPane2.setDividerLocation(200);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        puzzleDisplay.setText("Here be Riddles");
        puzzleDisplay.setEnabled(false);
        puzzleDisplay.setMinimumSize(new java.awt.Dimension(300, 300));
        puzzleDisplay.setName(""); // NOI18N
        puzzleDisplay.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(puzzleDisplay);

        jSplitPane2.setTopComponent(jScrollPane3);

        jTextField2.setEditable(false);
        jTextField2.setText("Input");

        SubmitAnswerButton.setText("Submit");
        SubmitAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitAnswerButtonActionPerformed(evt);
            }
        });

        SkipButton.setText("Skip (-30 HP)");
        SkipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(AnswerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(SubmitAnswerButton)
                .addGap(29, 29, 29)
                .addComponent(SkipButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AnswerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitAnswerButton)
                    .addComponent(SkipButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel1);

        menuFileDropdown.setText("File");

        quitMenuButton.setText("Quit");
        quitMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuButtonActionPerformed(evt);
            }
        });
        menuFileDropdown.add(quitMenuButton);

        menuBar.add(menuFileDropdown);

        menuEditDropdown.setText("Edit");
        menuBar.add(menuEditDropdown);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Menu Option Handling
    private void quitMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitMenuButtonActionPerformed

    private void SubmitAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitAnswerButtonActionPerformed
        checkAnswer();
    }//GEN-LAST:event_SubmitAnswerButtonActionPerformed

    private void SkipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkipButtonActionPerformed
        skipPuzzle();
    }//GEN-LAST:event_SkipButtonActionPerformed

    public static void puzzleScreen(Player TedRose) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuzzleScreen(TedRose).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerBox;
    private javax.swing.JButton SkipButton;
    private javax.swing.JButton SubmitAnswerButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEditDropdown;
    private javax.swing.JMenu menuFileDropdown;
    private javax.swing.JTextPane puzzleDisplay;
    private javax.swing.JMenuItem quitMenuButton;
    // End of variables declaration//GEN-END:variables
    
    private void startPuzzle() { 
        puzzle = new Puzzle();
        
        puzzle.newPuzzle();
        
        puzzleDisplay.setText(puzzle.puzzleText);
        
        this.incorrectAnswers = 0;
    }
    
    private void checkAnswer() {
        if (puzzle.checkAttempt(AnswerBox.getText())) {
            correctAnswer();
        } else {
            incorrectAnswer();
        }
    }
    
    private void correctAnswer() {
        Ted.increaseHP(15);
        finishPuzzle(Status.Correct); 
    }
    
    private void incorrectAnswer() {
        Ted.decreaseHP(10);
        this.incorrectAnswers += 1;
        
        JOptionPane.showMessageDialog(this, "Incorrect!", "Incorrect", JOptionPane.WARNING_MESSAGE);
        
        if (Ted.HP <= 0) {
            finishPuzzle(Status.OutOfHealth);
        }
        
        if (incorrectAnswers >= 3) {
            finishPuzzle(Status.Incorrect);
        }
    }
    
    private void skipPuzzle() {
        Ted.decreaseHP(30);
        
        if (Ted.HP <= 0) {
            finishPuzzle(Status.OutOfHealth);
        }
        
        finishPuzzle(Status.Skipped);
    }
    
    private void finishPuzzle(Status result) {
        
        switch (result) {
            case Correct:
                JOptionPane.showMessageDialog(this, "Correct!", "Correct", JOptionPane.INFORMATION_MESSAGE);
                break;
            case Incorrect:
                JOptionPane.showMessageDialog(this, "3 Attempts used!", "Incorrect", JOptionPane.ERROR_MESSAGE);
                break;
            case Skipped:
                JOptionPane.showMessageDialog(this, "Skipped!", "Skipped", JOptionPane.WARNING_MESSAGE);
                break;
            case OutOfHealth:
                JOptionPane.showMessageDialog(this, "You have run out of health! Restart the game to try again.", "Game Over", JOptionPane.ERROR_MESSAGE);
                dispose();
                System.exit(0);
            case WinCon:
                JOptionPane.showMessageDialog(this, "You Win! Restart the game to play again!", "Winner Winner Bagel Dinner", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                System.exit(0);
        }
        
        CurrentRoom.isLocked = false;
        dispose();
        
    }
    
}
